logo.png
bmstu-iu9/ptp2021-2-bitmap-editor pull request #4
Opened 2021-07-18 19:42 UTC by cupotato

добавлен логотип

2021-07-18 19:48 UTC, Mazdaywik requested changes
Теперь добавьте его в `README.md`:
```patch
 # ptp2021-2-bitmap-editor
+ [logo.png](icons/logo.png)
 
 Растровый графический редактор
+
 Участники команды:
 * Яровикова Анастасия (капитан) - https://github.com/ynastt
 *  Василовская Дарья  - https://github.com/vicadlsn
 * Лысенко Василий  -  https://github.com/KarumaRey
 * Сарварова Мария - https://github.com/cupotato
 * Жовтяк Ярослав - https://github.com/Dibydo
```

2021-07-18 20:21 UTC, cupotato commented
> Теперь добавьте его в `README.md`:
> 
> ```diff
>  # ptp2021-2-bitmap-editor
> + [logo.png](icons/logo.png)
>  
>  Растровый графический редактор
> +
>  Участники команды:
>  * Яровикова Анастасия (капитан) - https://github.com/ynastt
>  *  Василовская Дарья  - https://github.com/vicadlsn
>  * Лысенко Василий  -  https://github.com/KarumaRey
>  * Сарварова Мария - https://github.com/cupotato
>  * Жовтяк Ярослав - https://github.com/Dibydo
> ```

2021-07-18 20:22 UTC, cupotato commented
добавила, спасибо.

2021-07-19 09:28 UTC, Mazdaywik commented
Добавлять надо в этой же ветке.

2021-07-19 09:33 UTC, Mazdaywik requested changes
Пересаживайте эту ветку на актуальный `main` и исправляйте в `README.md` ссылку на логотип.
```Bash
git checkout main
git pull
git checkout cupotato-patch-2
git rebase main
git push -f
```
А ссылка должна выглядеть так:
```Markdown
[logo.png](icons/logo.png)
```

2021-09-15 14:16 UTC, Mazdaywik commented
Доделать там всего ничего было.

2021-09-18 12:10 UTC, merged