Add files via upload
bmstu-iu9/ptp2021-2-bitmap-editor pull request #7
Opened 2021-07-25 19:10 UTC by cupotato

2021-07-25 19:35 UTC, Mazdaywik requested changes
Поправьте также ссылку в `README.md`. В этой же ветке.

2021-09-15 14:15 UTC, Mazdaywik commented
Не, ну зачем же закрывать?

2021-09-16 05:53 UTC, ynastt commented
У человека возникли некоторые трудности => решили, что удалить ветку и сделать заново будет проще. Только поэтому. Но cupotato разберётся

2021-09-16 12:19 UTC, Mazdaywik approved these changes

2021-09-16 12:19 UTC, Mazdaywik commented
Вливайте! А `README.md` потом поправите.

2021-09-16 12:28 UTC, merged